server:
  port: 31002
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_cm
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03
    routingKey: 5e946777429ac4404d6801b2	#此routingKey为门户站点ID